# Generated by Django 4.2.10 on 2024-03-16 13:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testerhubback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerhubback.category', verbose_name='Категория теста'),
        ),
        migrations.CreateModel(
            name='TestSumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Отправленные ответы'), size=None)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerhubback.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerhubback.customuser', verbose_name='Пользователь')),
            ],
        ),
    ]
