# Generated by Django 4.2.10 on 2024-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testerhubback', '0002_alter_test_category_testsumission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsumission',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты теста'},
        ),
        migrations.AddField(
            model_name='testsumission',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
