# Generated by Django 4.2.10 on 2024-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testerhubback', '0003_alter_testsumission_options_testsumission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testsimg/', verbose_name='Изображение'),
        ),
    ]
